version: '3.9'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
    ports:
      - ":3307:3306"
    volumes:
      - ./data:/var/lib/mysql
